GET https://localhost:7002/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiRmF6dWwgSHVzc2FpbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImV4cCI6MTc0NzMwNjkyNSwiaXNzIjoiTW92aWVzQVBJIiwiYXVkIjoiTW92aWVzQVBJVXNlcnMifQ.UlvxPYMrdPgRh8o7EDGlDPiqmsi12AmuVbknwBfUlVw

###
GET https://localhost:7002/movies/7

###
POST https://localhost:7002/movies
Content-type:application/json 

{
  "Name": "The Batman",
  "Price": 30,
  "ReleaseDate": "2024-05-10",
  "GenreId": 3
}


###
PUT https://localhost:7002/movies/7
Content-type:application/json 
{
  "Name": "The Batman",
  "Price": 40,
  "ReleaseDate": "2024-07-10",
  "GenreId": 1
}

###
DELETE https://localhost:7002/movies/6


###
POST https://localhost:7002/signup
Content-type:application/json 

{
  "Username": "Fazul Hussain",
  "Password": "Fazal123"

}


###
POST https://localhost:7002/login
Content-type:application/json 

{
  "Username": "Fazul Hussain",
  "Password": "Fazal123"

}


###
GET https://localhost:7002/get-users
